version: '2'
services:
  db:
    image: postgres:15
    container_name: database
    user: root
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2022      
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Volumen persistente para los datos
      # - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - '5450:5432' # Puerto expuesto para la base de datos

  api:
    build:
      context: ./backend # Ruta al directorio de backend
    container_name: backend
    depends_on:
      - db # Esperar a que la base de datos esté lista antes de levantar este servicio
    # environment:
    #   - DB_USER=postgres
    #   - DB_PASSWORD=2022
    #   - DB_HOST=database
    #   - DB_PORT=5450
    #   - DB_NAME=todolist
    env_file:
      - ./backend/.env
    ports:
      - '8000:8000' # Exponer el puerto del backend
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  frontend:
    build:
      context: ./frontend # Ruta al directorio de Nuxt.js
    container_name: frontend
    depends_on:
      - api # Esperar a que la API esté lista antes de levantar este servicio
    environment:
      - NUXT_API_URL=http://localhost:8000 # URL para conectar el frontend con el backend
    env_file:
      - ./frontend/.env
    ports:
      - '3000:3000' # Exponer el puerto del frontend
    # volumes:
    #   - ./frontend:/app
    command: pnpm run preview
    restart: always

volumes:
  postgres_data:
    driver: local
