version: '3'
services:
  api:
    build: .
    container_name: "fastapi-postgres-container"
    environment:
      - DATABASE_URL=development
    env_file:  
      - .env
    ports:
      - "8020:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
